<?php

return [
    'commons' => [
        'Không trả lời đâu, ahihi đồ ngốc',
        'Đi ra ngoài shopping roài',
        'Lát rảnh nói nghe',
        'Khùng quá má',
        'Rảnh hơm',
        'Ừ',
        "Ok cưng",
        '(h)',
        'Mơ đi cưng',
        'Không phải',
        'Phải',
        'Anh Chí đẹp trai nhứt',
        'Vân và Vy đều mập',
        'Hôm nay có ăn sáng chưa ?',
        'Ngày mai có đi làm không chế',
        'Đói quá',
        'Rảnh',
        'Mai là ngày mấy vậy',
        'Vân có bồ chưa',
        'Vy chừng nào hết ế',
        'Lễ mập',
        'Mai tao đi chơi rồi, mày đi hơm',
        'Trà sữa đê, tao bao.',
        'Lạnh quá cho cái mền đê',
        'Mấy tuổi rồi',
        'Ngu thật',
        'Hơm phải đâu',
        'Gà xinh đẹp',
        'Gà biết gà đẹp',
        'Gà chưa có trứng nên đừng có hỏi gà',
    ]
];
